apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scanendpoints
  name: scanendpoints
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanendpoints
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scanendpoints
    spec:
      containers:
        - name: scanendpoints
          envFrom:
            - secretRef:
                name: db-creds
          env:
            - name: UDP_FLOOD_PACKET_SIZE
              value: "3"
            - name: NUM_OF_FLOOD_THREADS
              value: "10"
            - name: SLEEP_BETWEEN_FLOOD
              value: "5"
            - name: UDP_PORT_MIN
              value: "1024"
            - name: UDP_PORT_MAX
              value: "65534"
          image: 441218111557.dkr.ecr.us-west-2.amazonaws.com/udpflooder:aarch64
          imagePullPolicy: Always
          command: ["/scanendpoints.py"]
